// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBGqk9xmRrNkHNBeJJs2ZZvxEEGltUi0Lw',
    appId: '1:328797253244:web:1ace563223c0ecbb0c63f9',
    messagingSenderId: '328797253244',
    projectId: 'fir-e73c7',
    authDomain: 'fir-e73c7.firebaseapp.com',
    storageBucket: 'fir-e73c7.firebasestorage.app',
    measurementId: 'G-Q3M1BELHCY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCYT54r_6se9GVNWtfdXl0-FpjF6epP-nQ',
    appId: '1:328797253244:android:0bd0cad161ad7d160c63f9',
    messagingSenderId: '328797253244',
    projectId: 'fir-e73c7',
    storageBucket: 'fir-e73c7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB-H267H4GeC5JUOAMSYMO9prwYXz50qJs',
    appId: '1:328797253244:ios:718e1191f10f53130c63f9',
    messagingSenderId: '328797253244',
    projectId: 'fir-e73c7',
    storageBucket: 'fir-e73c7.firebasestorage.app',
    iosBundleId: 'A.Ahad.firebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB-H267H4GeC5JUOAMSYMO9prwYXz50qJs',
    appId: '1:328797253244:ios:718e1191f10f53130c63f9',
    messagingSenderId: '328797253244',
    projectId: 'fir-e73c7',
    storageBucket: 'fir-e73c7.firebasestorage.app',
    iosBundleId: 'A.Ahad.firebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBGqk9xmRrNkHNBeJJs2ZZvxEEGltUi0Lw',
    appId: '1:328797253244:web:010fa471a8db5b250c63f9',
    messagingSenderId: '328797253244',
    projectId: 'fir-e73c7',
    authDomain: 'fir-e73c7.firebaseapp.com',
    storageBucket: 'fir-e73c7.firebasestorage.app',
    measurementId: 'G-NRX74TB1SY',
  );
}
